### PR TITLE
feat: add hbase-connectors repo for hbase spark connector

### LINKED ISSUE #3: Add HBase Spark connector
Add branch `hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT` from https://github.com/TOSIT-IO/hbase-connectors to build HBase Spark connector.

### PR DESCRIPTION
**Pull request by rpignolet**
#### Which issue(s) this PR fixes:

Fixes #3 

#### Additional comments:

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0) and that you give permission to [TOSIT](https://www.tosit.io/),
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [x] I hereby agree to grant [TOSIT](https://www.tosit.io/) a copyright license to use my contributions.

### CODE REVIEW

**Comment by rpignolet** [comment]
@mehdibn @gboutry @leopaul36 The Maven build is not working, here the log:

```
[INFO] ----------< org.apache.hbase.connectors.spark:hbase-spark-it >----------
[INFO] Building Apache HBase - Spark Integration Tests 1.0.0-TDP-0.1.0-SNAPSHOT [7/8]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Failure to transfer org.glassfish:javax.el/maven-metadata.xml from https://maven.java.net/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of java.net.Releases has elapsed or updates are forced. Original error: Could not transfer metadata org.glassfish:javax.el/maven-metadata.xml from/to java.net.Releases (https://maven.java.net/content/repositories/releases): Access denied to: https://maven.java.net/content/repositories/releases/org/glassfish/javax.el/maven-metadata.xml , ReasonPhrase:Forbidden.
[WARNING] Failure to transfer org.glassfish:javax.el/maven-metadata.xml from https://maven.java.net/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of jvnet-nexus-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.glassfish:javax.el/maven-metadata.xml from/to jvnet-nexus-snapshots (https://maven.java.net/content/repositories/snapshots): Access denied to: https://maven.java.net/content/repositories/snapshots/org/glassfish/javax.el/maven-metadata.xml , ReasonPhrase:Forbidden.
[WARNING] The POM for org.apache.hbase.connectors.spark:hbase-spark:jar:1.0.0-TDP-0.1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache HBase Connectors 1.0.0-TDP-0.1.0-SNAPSHOT:
[INFO] 
[INFO] Apache HBase Connectors ............................ SUCCESS [  1.797 s]
[INFO] Apache HBase - Kafka ............................... SUCCESS [  0.140 s]
[INFO] Apache HBase - Model Objects for Kafka Proxy ....... SUCCESS [  2.233 s]
[INFO] Apache HBase - Kafka Proxy ......................... SUCCESS [  5.095 s]
[INFO] Apache HBase - Spark ............................... SUCCESS [  0.110 s]
[INFO] Apache HBase - Spark Connector ..................... SUCCESS [ 39.490 s]
[INFO] Apache HBase - Spark Integration Tests ............. FAILURE [  0.172 s]
[INFO] Apache HBase Connectors - Assembly ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  49.471 s
[INFO] Finished at: 2022-10-16T09:43:41Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hbase-spark-it: Could not resolve dependencies for project org.apache.hbase.connectors.spark:hbase-spark-it:jar:1.0.0-TDP-0.1.0-SNAPSHOT: Failure to find org.apache.hbase.connectors.spark:hbase-spark:jar:1.0.0-TDP-0.1.0-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hbase-spark-it
```

I don't know why  `hbase-spark-it` search `hbase-spark` in remote repository.

**Comment by mehdibn** [comment]
If I remember correctly, I didn't have this issue as the local dependency was used.

**Comment by mehdibn** [comment]
Can you check if the `hbase-spark:jar:1.0.0-TDP-0.1.0-SNAPSHOT` exists in your `.m2` ?
If not, does it change after a `mvn intall` from `hbase-connectors/spark/` ?

**Comment by rpignolet** [comment]
@mehdibn

I ran these commands:
```
cd /build/hbase-spark-connector/spark
mvn clean install -Dspark.version=2.3.5-TDP-0.1.0-SNAPSHOT -Dscala.version=2.11.8 -Dscala.binary.version=2.11 -Dhadoop-three.version=3.1.1-TDP-0.1.0-SNAPSHOT -Dhbase.version=2.1.10-TDP-0.1.0-SNAPSHOT -DskipTests -Dhttps.proxyHost=squid -Dhttps.proxyPort=3128 -Dhttp.proxyHost=squid -Dhttp.proxyPort=3128 -Dmaven.repo.local=/build/m2
```

Outputs:
```
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ hbase-spark-2.3.5 ---
[INFO] Installing /build/hbase-spark-connector/spark/hbase-spark/target/hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT.jar to /build/m2/org/apache/hbase/connectors/spark/hbase-spark-2.3.5/1.0.0-TDP-0.1.0-SNAPSHOT/hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT.jar
[INFO] Installing /build/hbase-spark-connector/spark/hbase-spark/.flattened-pom.xml to /build/m2/org/apache/hbase/connectors/spark/hbase-spark-2.3.5/1.0.0-TDP-0.1.0-SNAPSHOT/hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT.pom
[INFO] 
[INFO] ----------< org.apache.hbase.connectors.spark:hbase-spark-it >----------
[INFO] Building Apache HBase - Spark Integration Tests 1.0.0-TDP-0.1.0-SNAPSHOT [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] Failure to transfer org.glassfish:javax.el/maven-metadata.xml from https://maven.java.net/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of java.net.Releases has elapsed or updates are forced. Original error: Could not transfer metadata org.glassfish:javax.el/maven-metadata.xml from/to java.net.Releases (https://maven.java.net/content/repositories/releases): Access denied to: https://maven.java.net/content/repositories/releases/org/glassfish/javax.el/maven-metadata.xml , ReasonPhrase:Forbidden.
[WARNING] Failure to transfer org.glassfish:javax.el/maven-metadata.xml from https://maven.java.net/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of jvnet-nexus-snapshots has elapsed or updates are forced. Original error: Could not transfer metadata org.glassfish:javax.el/maven-metadata.xml from/to jvnet-nexus-snapshots (https://maven.java.net/content/repositories/snapshots): Access denied to: https://maven.java.net/content/repositories/snapshots/org/glassfish/javax.el/maven-metadata.xml , ReasonPhrase:Forbidden.
[WARNING] The POM for org.apache.hbase.connectors.spark:hbase-spark:jar:1.0.0-TDP-0.1.0-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache HBase - Spark 1.0.0-TDP-0.1.0-SNAPSHOT:
[INFO] 
[INFO] Apache HBase - Spark ............................... SUCCESS [  2.430 s]
[INFO] Apache HBase - Spark Connector ..................... SUCCESS [ 43.600 s]
[INFO] Apache HBase - Spark Integration Tests ............. FAILURE [  0.162 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  46.665 s
[INFO] Finished at: 2022-11-02T11:00:51Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hbase-spark-it: Could not resolve dependencies for project org.apache.hbase.connectors.spark:hbase-spark-it:jar:1.0.0-TDP-0.1.0-SNAPSHOT: Failure to find org.apache.hbase.connectors.spark:hbase-spark:jar:1.0.0-TDP-0.1.0-SNAPSHOT in https://repository.apache.org/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of apache.snapshots has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :hbase-spark-it
```

Content of `.m2` for `hbase-spark` **after** the `mvn install` command above:
```
$ ls -l /build/m2/org/apache/hbase/connectors/spark/hbase-spark/1.0.0-TDP-0.1.0-SNAPSHOT/
total 12
-rw-r--r-- 1 builder builder 257 Nov  2 10:59 hbase-spark-1.0.0-TDP-0.1.0-SNAPSHOT.jar.lastUpdated
-rw-r--r-- 1 builder builder 257 Nov  2 10:59 hbase-spark-1.0.0-TDP-0.1.0-SNAPSHOT.pom.lastUpdated
-rw-r--r-- 1 builder builder 245 Nov  2 10:59 resolver-status.properties
```

But If I look at where Maven install the `hbase-spark.jar`:
```
$ ls -l /build/m2/org/apache/hbase/connectors/spark/hbase-spark-2.3.5/1.0.0-TDP-0.1.0-SNAPSHOT
total 836
-rw-r--r-- 1 builder builder    238 Nov  2 11:00 _remote.repositories
-rw-r--r-- 1 builder builder 816679 Nov  2 11:00 hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT.jar
-rw-r--r-- 1 builder builder  26147 Nov  2 11:00 hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT.pom
-rw-r--r-- 1 builder builder    766 Nov  2 11:00 maven-metadata-local.xml
```

The artifact name is `hbase-spark` or `hbase-spark-2.3.5` ?

**Comment by mehdibn** [comment]
I see the issue:

- in tdp, we manage more than one spark version 
- in this specific branch (`hbase-spark-2.3.5-1.0.0-TDP-0.1.0-SNAPSHOT `), you can do `mvn compile | install` without specifying the dependencies versions 
- in my case, as i built the project with initial versions then with specific one, and, i missed this [change](https://github.com/TOSIT-IO/hbase-connectors/pull/3) that did generate an error in my case

**Comment by rpignolet** [comment]
The build command inside the README in now working with https://github.com/TOSIT-IO/hbase-connectors/pull/3.

**Comment by rpignolet** [comment]
@mehdibn Can you tell me if the build command inside the README is correct ? Inside the `hbase-connector` README there are 2 commands for build and I don't know the command to use.

**Comment by mehdibn** [comment]
@rpignolet both of them are correct, but, i suggest using this one in order to be sure to have the adequate dependencies:
```
mvn clean install \
  -Dspark.version=2.3.5-TDP-0.1.0-SNAPSHOT \
  -Dscala.version=2.11.8 \
  -Dscala.binary.version=2.11 \
  -Dhadoop-three.version=3.1.1-TDP-0.1.0-SNAPSHOT \
  -Dhbase.version=2.1.10-TDP-0.1.0-SNAPSHOT \
  -DskipTests \
  -Dmaven.javdoc.skip=true \
  -Dcheckstyle.skip=true \
  -Dfindbugs.skip=true \
  -Dspotbugs.skip=true \
  --batch-mode \
  -fae
```

**Review by mehdibn — APPROVED** [review]

**Pull request merged**
